
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-website
  labels:
    app: hello-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-website
  template:
    metadata:
      labels:
        app: hello-website
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: hello
        image: ghcr.io/rosenvold-technology/hello-world
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
