apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - service.yaml
images:
  - name: ghcr.io/rosenvold-technology/hello-world
    newTag: latest
